### ISSUE TITLE
trade history shows ongoing trade as completed

### ISSUE THREAD

**Issue by jorian** [particle4dev/hyperdex#4]
When a swap is started, the trade is immediately listed as 'Completed'. It should however show the intermediary steps of a trade.

![image](https://user-images.githubusercontent.com/10341677/68665895-2d595b80-0543-11ea-8254-d43cccda6368.png)

while the actual trade shows:

![image](https://user-images.githubusercontent.com/10341677/68665915-3813f080-0543-11ea-8a79-61ef035c7a30.png)

**Comment by jorian** [comment]
Simplest solution in my opinion would be to show the status as Pending, and when a user clicks on it, he / she can track the status of the swap.

**Comment by particle4dev** [comment]
@jorian I think it's a little confusing here
Right now, there is no concept of `swap` in the app
Only concept of `orders` (Please read https://github.com/atomiclabs/hyperdex/issues/615)
So there is 2 type of orders: `maker` order and `taker` order
Your swap is `taker` order
and it's immediately listed as 'Completed' because it's filled
but its swap is still running
Does this make sense?

**Comment by jorian** [comment]
Yes it makes sense. Though I'm not sure if this is UX-friendly, since a swap can still fail. The user might think the order is completed, while the actual swap might have failed. 

So, a concept of swap might actually be helpful, just for UX.

**Comment by jorian** [comment]
In the screenshot in the README of this repo, you can see how it was done in the first version of marketmaker: 

![image](https://user-images.githubusercontent.com/10341677/68866845-4bff5400-06f5-11ea-86cd-15652b5ca7fe.png)

Now I understand there are some more steps involved, so this might be an issue to be implemented on the longer term.
